services:
  postgres:
    image: postgres:17
    container_name: moviemovie_db
    environment:
      POSTGRES_USER: moviemovie
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
